@token = eyJraWQiOiJrU2VlVHRiSldkYjdVc1VMUE1iNVAzcVBIR0tBSjR2eWpMQnVCRDNFN3JNIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULkpVOEY5RVktUTJhX1cyRlVYNFdQSjUyZm4tYU5zUkxqRklhVUV1eHIxSFEiLCJpc3MiOiJodHRwczovL2Rldi00OTkyOTgwLm9rdGEuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTYyMjM4MjQ2MSwiZXhwIjoxNjIyMzg2MDYxLCJjaWQiOiIwb2EzOG5sYTNQRE1WY0ZmODVkNiIsInVpZCI6IjAwdTJ1YmtndnlzcDlVb3BrNWQ2Iiwic2NwIjpbIm9wZW5pZCJdLCJzdWIiOiJkb25pbGVAZ21haWwuY29tIn0.BkzG11APB10o5WTymBWURE3-CHGkY07tKxt567ug1bPTsIn7LKkOE61HcHJE6F7m78IN84Rd00YCF30ktjOSmIw4KM5eDPdbd8F_rAeWXqFawFAtQpgIXKZ5V5fDXbVbWkzXOYHLnM2_QDHOAsn8IfdGDptL28DdB42rqa-uVGb-oyX_aketJtcGlM6-fWs0pSpxKNyE4zYG4-NWwey8Bpd7wJKVGKMWm-YiTpo3nnZxhaoHd4UBLOqwzrZyBeo74L51Fqu0QUEQl5yvU6hYnUvT8r3Av8KFuNw685FPBtf740uAKiYmkVFFaBlR6qNePsntXoZFy0m_HqqhAEUUAg

###
GET http://localhost:5000/blog-posts

###
# Return 400 Bad Request - No entity included in HTTP body
POST http://localhost:5000/blog-posts
Authorization: Bearer {{token}}
Content-Type: application/json

###
# Return 200 OK
POST http://localhost:5000/blog-posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "test title",
    "post": "test post",
    "writtenDate": "2021-06-07T07:54:00.0Z",
    "releaseDate": "2021-06-07T07:54:00.0Z"
}
