POST http://localhost:5000/blog-posts
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJrIiwibmJmIjoxNjA5MzAyNDU2LCJleHAiOjE2MDkzODg4NTYsImlhdCI6MTYwOTMwMjQ1Nn0._uQMpuEKc7P1-GPXyPeWh1NCbWEjgxJabyMWLos-tbo70vNCn1WHC5uHV1MAR4K7ryO_eTZ_OaINVpZlvhYGrQ