name: test
on:
  push:
    branches: master

jobs:
  runs-on: ubuntu-18.04
  build:
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: echo Hello, World
      run: echo Hello, Mark Donile!