name: continuous-integration

on:
  push:
    branches: master

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: echo Hello, World
      run: echo Hello, Mark Donile!