name: continuous-integration

on:
  push:
    branches: master

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.8.0'
    - name: install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402'
    - name: execute build script
      run: ./build/build.sh
    - name: upload build artifact(s)
      uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts
  test:
    needs: [build]
    steps:
      - name: download build artifact(s)
        uses: actions/download-artifact@v1
        with:
          name: artifacts
      - name: list artifacts
        run: ls -lahR ./artifacts
